### ISSUE TITLE
Connection reset by peer in connection to api.bol.com:443

### ISSUE THREAD

**Issue by liamseys** [developersbolcom/developersbolcom#75]
Hello

Recently we are getting the following message from the API: Connection reset by peer in connection to api.bol.com:443, we are sending in requests according to the given API rate-limits. Has anyone experienced this issue before?

Best
Liam

**Comment by karan-indigoerp** [comment]
We are getting this error and sometimes 
`504 Server Error: Gateway Timeout for url`

But only with the demo endpoints
